INSERT INTO
  paises (nombre)
VALUES
  ('Burundi'),
  ('Brazil'),
  ('Bosnia and Herzegovina'),
  ('Bhutan'),
  ('Belize'),
  ('Benin'),
  ('Bahrain'),
  ('Bangladesh'),
  ('Barbados'),
  ('Austria'),
  ('Australia'),
  ('Angola'),
  ('Algeria'),
  ('Albania'),
  ('Zimbabwe'),
  ('Yemen'),
  ('Venezuela'),
  ('Vietnam'),
  ('Uruguay'),
  ('Tunisia'),
  ('Trinidad and Tobago'),
  ('Togo'),
  ('Thailand'),
  ('Swaziland'),
  ('Sweden'),
  ('Spain'),
  ('Slovakia'),
  ('Slovenia'),
  ('Solomon Islands'),
  ('Somalia'),
  ('Colombia');

INSERT INTO
  ciudades (id_pais, nombre)
VALUES
  (1, 'Gitega'),
  (2, 'São Paulo'),
  (3, 'Sarajevo'),
  (4, 'Thimphu'),
  (5, 'Belize City'),
  (6, 'Porto-Novo'),
  (7, 'Manama'),
  (8, 'Dhaka'),
  (9, 'Bridgetown'),
  (10, 'Vienna'),
  (11, 'Perth'),
  (12, 'Luanda'),
  (13, 'Algiers'),
  (14, 'Tirana'),
  (15, 'Harare'),
  (16, 'Sanaa'),
  (17, 'Caracas'),
  (18, 'Hanoi'),
  (19, 'Montevideo'),
  (20, 'Tunis'),
  (21, 'Port of Spain'),
  (22, 'Lomé'),
  (23, 'Bangkok'),
  (24, 'Mbabane'),
  (25, 'Stockholm'),
  (26, 'Madrid'),
  (27, 'Bratislava'),
  (28, 'Ljubljana'),
  (29, 'Honiara'),
  (30, 'Mogadishu'),
  (1, 'Ngozi'),
  (2, 'Curitiba'),
  (3, 'Mostar'),
  (4, 'Punakha'),
  (5, 'Corozal'),
  (6, 'Cotonou'),
  (7, 'Muharraq'),
  (8, 'Chittagong'),
  (9, 'Speightstown'),
  (10, 'Graz'),
  (11, 'Melbourne'),
  (12, 'Huambo'),
  (13, 'Oran'),
  (14, 'Vlorë'),
  (15, 'Bulawayo'),
  (16, 'Aden'),
  (17, 'Maracaibo'),
  (18, 'Ho Chi Minh City'),
  (19, 'Punta del Este'),
  (20, 'Sfax'),
  (21, 'San Fernando'),
  (22, 'Atakpamé'),
  (23, 'Chiang Mai'),
  (24, 'Manzini'),
  (25, 'Gothenburg'),
  (26, 'Valencia'),
  (27, 'Košice'),
  (28, 'Celje'),
  (29, 'Auki'),
  (30, 'Hargeisa'),
  (1, 'Rumonge'),
  (2, 'Florianópolis'),
  (3, 'Tuzla'),
  (4, 'Wangdue Phodrang'),
  (5, 'Dangriga'),
  (6, 'Parakou'),
  (7, 'Riffa'),
  (8, 'Sylhet'),
  (9, 'Oistins'),
  (10, 'Linz'),
  (11, 'Hobart'),
  (12, 'Lubango'),
  (13, 'Constantine'),
  (14, 'Sarandë'),
  (15, 'Mutare'),
  (16, 'Taiz'),
  (17, 'Barquisimeto'),
  (18, 'Da Nang'),
  (20, 'Kairouan'),
  (21, 'Princes Town'),
  (22, 'Kpalimé'),
  (23, 'Udon Thani'),
  (24, 'Mhlume'),
  (25, 'Malmö'),
  (26, 'Zaragoza'),
  (27, 'Prešov'),
  (28, 'Novo Mesto'),
  (29, 'Honiara'),
  (30, 'Berbera'),
  (31, 'Bucaramanga');

CREATE PROCEDURE generate_random_celphone()
BEGIN
  DECLARE counter INT DEFAULT 1;
  DECLARE random_celphone BIGINT DEFAULT 0;
  WHILE counter <= 120 DO
    SET random_celphone = FLOOR(RAND() * 100000000000) + UUID_SHORT();
    INSERT INTO telefonos (numero) VALUES (random_celphone);
    SET counter = counter + 1;
  END WHILE;
END;
CALL generate_random_celphone();

INSERT INTO
  tipos_servicios (nombre)
VALUES
  ('Nacional'),
  ('Internacional'),
  ('Express'),
  ('Estandar');

INSERT INTO
  estados_seguimientos (nombre)
VALUES
  ('Recibido'),
  ('En Transito'),
  ('Retenido en aduana');

INSERT INTO
  marcas (nombre)
VALUES
  ('Toyota'),
  ('Harley-Davidson'),
  ('Bayliner'),
  ('Ford'),
  ('Yamaha'),
  ('Sea-Doo'),
  ('Chevrolet'),
  ('Kawasaki'),
  ('MasterCraft'),
  ('Honda'),
  ('Suzuki'),
  ('Mercedes-Benz'),
  ('BMW'),
  ('Polaris'),
  ('Ferrari'),
  ('Lamborghini'),
  ('Porsche'),
  ('Volkswagen'),
  ('Nissan'),
  ('Mazda'),
  ('Hyundai'),
  ('Kia'),
  ('Ducati'),
  ('Triumph'),
  ('Aprilia'),
  ('Mitsubishi'),
  ('Jeep'),
  ('Land Rover'),
  ('Audi'),
  ('Volvo'),
  ('Scania'),
  ('MAN'),
  ('Iveco'),
  ('Renault'),
  ('Peugeot'),
  ('Citroen'),
  ('Skoda'),
  ('Seat'),
  ('Chrysler'),
  ('Dodge'),
  ('Ram'),
  ('GMC'),
  ('Buick'),
  ('Cadillac'),
  ('Lincoln'),
  ('Mercury'),
  ('Fiat'),
  ('Alfa Romeo'),
  ('Maserati'),
  ('Lancia'),
  ('Jaguar'),
  ('Land Rover'),
  ('Aston Martin'),
  ('Bentley'),
  ('Rolls-Royce'),
  ('Mini'),
  ('Smart'),
  ('Tesla'),
  ('Riviera'),
  ('Regal'),
  ('Sea Ray'),
  ('Boston Whaler'),
  ('Grady-White'),
  ('Hatteras'),
  ('Azimut'),
  ('Sunseeker'),
  ('Ferretti'),
  ('Riva'),
  ('Princess'),
  ('Jeanneau'),
  ('Beneteau'),
  ('Hunter'),
  ('Catalina'),
  ('J/Boats'),
  ('Bennington'),
  ('Regal'),
  ('Chaparral'),
  ('Cobalt'),
  ('Malibu'),
  ('MasterCraft'),
  ('Supra'),
  ('Moomba'),
  ('Tige'),
  ('Axis'),
  ('Supreme'),
  ('Centurion'),
  ('Ski Nautique'),
  ('Correct Craft'),
  ('Boston Whaler'),
  ('Grady-White'),
  ('Hatteras'),
  ('Azimut'),
  ('Sunseeker'),
  ('Ferretti'),
  ('Riva'),
  ('Princess'),
  ('Jeanneau'),
  ('Beneteau'),
  ('Hunter'),
  ('Catalina'),
  ('J/Boats'),
  ('Bennington'),
  ('Regal'),
  ('Chaparral'),
  ('Cobalt'),
  ('Malibu'),
  ('MasterCraft'),
  ('Supra'),
  ('Moomba'),
  ('Tige'),
  ('Axis'),
  ('Supreme'),
  ('Centurion'),
  ('Ski Nautique'),
  ('Correct Craft');


